language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
- pip install codecov
env:
  secure: ctBdFXeuYY4HaMV3OIEFoN5wj0eZhdx9jfCZemyx9vl/8iHdN+eAhkA14wTgacSpF/bEliOCN9Km9MAGZd76KmORz+lvlCaK15vL1UIfxLAZ8yNaLT/81qZXERIWlXamZcPbdAgN3lFCwbLf6gn13uB4wgaL2XLr4e0w/fsp6BtRMHUFZ/y/yj5MvbtzKu4CBbq/qkR6hCUgj9ueKs67RpSjM7n+hQf+Zp4KusIiBVkslTJPE8dJY9qDoVGWNQWAvScE/BbjzRNWH33rDXOeYDflDwfwKyZJE+3KY7u+4bqtjI+4pYyTvT3hCoQSbf+7h20XvhphOTRBLg/TvhLLJoy7vYS+5llgiENUzjy/HcO8nMjRCVjicn/tYR5x+OmAhMtYLF2K38NDLvi1Ndo48c3x0qJ7H9UKpAmCo7t5NPuzWChXbE9E5faDxUpOb69DKDUXjKxvFjoCqXN8zsDl9WvqVETfPdhcjbU2ejmVPfoVUY4XuippTgss6aW5t1ODgCoiQ22GOeFNUxlB1sWayh4u4Hq3DuFgEWXdqy9Xmwe7B490BJnsdD+Ikg1uoZmJ+jY8KUNP4aXYhYRGmNAX631QGFGAsaH5NQSCcLS6BmIwRtLbaf6vvdRwkDV2q3vwRxAxGSROBlh8HadTwKDbhCnlZit2R+FDqKrW72LP96I=
script:
- coverage run computer-vision-api.py $vision_API_key $face_API_key
after_success:
- codecov
