language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
env:
- secure: xX+OmfAJ4yVYwkb9eZr1zfxFnBjKIf1uVFi2ExsKuRguyATYNkgvw/ZoPviraLvRgy+onDZWlH2T9ybIE7LdHL2zl79E2DKEguV3TjuawW379JiBEMKgzLgr9UQimb7iq7v0rtIYkSXcLAd98zAMYLdQSZM04ldr3XDyBfbr3Qj8bJbR1jjPRLFMcibuPgKIsPyzdnaXO36R00P2gb3A/SREk51kFluHpKjhHd7lCmIT3V+J/Q5vEZCHEeAlEXDT6+q6Pq+McAH+U1mfbfe+3k137cxYk677gI5ZNt/wbBEkl+RTcMTIhgtyZMDU4a5oqpti1sHDBat95A5qu6xYYO7nPZPSI6YY+X8Ki8YYNF5i9zZkXnCZ1+XWDHJuMaOVb+F6CeCHpSi7GXyD4tPrdxsqlODlxuH4XCOLorIWgml4NVc7G+tke8N9epPoyKKNN4ev5W3/ScK51nL6fTFwL4ZIzkdlBzxGc3QT9V26dnA+7XYCE0TZfOJR5a5HhLH7Gu6x3ttNlN9m1bGTZKyK5Agzov3JyW1POWdG39SXA+7f19Axcqozdzw0a2k3aVJRfvcdPC4sW/uriLdoovW4EyON1ba/Mb42kP9Lwu2hmyHNjy1uLmJYduMGs1dlwDqwqvYUmaW7ZjTdoJhA4GyIKnRaxPDRCRcl4UnYNC8WC2k=
- face_API_key=abcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
script:
- coverage run computer-vision-api.py $vision_API_key $face_API_key
after_success:
- codecov
