language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
env:
  secure: DzsHnVIa6lZj1idPpxbs76Io/iuqZizseYgg0leHQhQHuRRbXuUe0ByOnm8bzTuiVJUVzbSTE0DStm9jMZilYjXWplFX+7Dn6pP53KSDPmaW+/XtaMOZVD+mAPnWmtQeTV2S1bmPltOZeKBgEj5y6t5XW8lyrQ+68UCWyEezBqslstb6Vg//pwK4q5MYhH5FlQ9PnHfEfia0cIUUNuCfuL9ck950A61hKY0hsehNsmDhq4/2MG5JMn1ovzJsGU/jwhg91lS4wEGl2m5ztDvr3lxIFRppxodYkW/ZnX2B9idl/qXvIQr/YJAvhv84za8fxRj2UwGdqT8msDuOPCF9Rqq1Nrw5WIN6/nIpulAvrOgBO829CDXtHpTozaHZks89aQVQMgUDOA7m+jZFT7xA34IsWlPeb8yK2bKUExxAabddv3kZ6N99G+r2frnNq560mDsGedlkdIAdxgKwYQCCsZTDgDuOv7I6wTmvZrDhPRUuuRzh4nWA4PmNsud5JrxSQY8QIr3QB0ODccQhsaDpKzi3pMGo5HII+d3f7jFO8yh79Wb3Ab+oLzbvKlk1FlNNugz18tYizvB48YQPYlRkyKqTERcdh1sRFnBNCifiWd2tLggTbrCsqJXzsj4iU5zlTz7sWm1LlwQzXh0KKJz70GGQNvNa7QhBgsdehgUxCIw=
script:
- coverage run computer-vision-api.py $vision_API_key $face_API_key
after_success:
- codecov
