language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- secure: DCh4GS7qe8gBvKaiBolHP5lex2tP/LQczymyh61D6DbHEftWxeeP/0o0o2xSVgD5tsYFyoolB/yOgCQ07V7EwE5jrlfzCZiQqt/KwL31vtHf+ImEEyoENPknbGcd6Ceiy98auki6fQClK//hnAIpcMwJrnqWLZOja+o163Vtzdzd2Hot7sFzFzfgz2mleGeFQ9ENa4o9FrJQJniOtTBEjvV3AHtB9Qdj+fS79M+0Cer+UEUXfnS4Gbe3GKQ0sx39wPKG8VpQKlEtGYwFeea0iPqqKzeV0ObtaLkCSlPscxV7YiQCyA57L9BxBx+UiU1d2Vd251t+cTmbC0E4SlxMLsuAaB4JJCBejZbRuUkfB4Sk1FmWEUO7rTCZ/NZw7EOvuit98vpbjTaArqR0c01iECvvxwgx8oQ2Ewp6fSEdBD/gf/QrOW8IDPoRG3WD76ZEFj76AmdSD/XBY8YwDedkpK0nyY6ggSu715S7S2uPEWhbumLlePRkNwPLoX3cUOHqrNrAnKBKVbK74vgmvgAMYPKEWhsnOa67OEBYFHUJ9YZhwJvZObm7rX/Q7R3gP7h4I0Jj5shB7ad0CTgWUHWT9vXj43lgD+qSioKaHYqh+zCEnAooEPMjNA4tdOPsxaOSzkDVdr21CHPlnqvUb3h3Wu1r/YCVvCRzh7zb5wEcQW4=
after_success:
- codecov
