language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- secure: zIQPpVnjPyOW6bNp0lTYWv8xuZlv3lybS49h5ARBZ1Lh34Wmrywnvi3wTmQp97YTKAOCPw3WgbJgB2Jqj9UEbJ/YAl7Qfb0a4pGtyu0Rj3NoHCp0zYvqFGtFayDPmwCqYPwhJoOB4ED2bzkk8TemFZcgfX6EBC7JiDpTuemQI233DMiYI7DV5yeUSnEC4RxZqqZkz8DfUSxeFhPVFJOey2tqbkxhMgD0NWNbDCerhfHBPU1lluepiAa5fWq5zxNUznGpWc9OGlRO1VVad+v2BMpvPmol/23aiou2yS4JhOtr6EWME0q0UE0EPmA0UHi63Pb7ZM2FSmGztaavw0hyBBi0oIMVGm1FgGdUDRqWxc9ztwVEZfPx+oAtlXHU0gfy48A/GX4VJ5kzuX3TicQ7Lq6kbzk8CUduAhjl9ABMLuX+cw/SSnMiOI5h6J4i2wYj3LLbT39JvEgbRYt+1T2KiCuodqy3+SuKuUJp/PRoJVnAigoI9EfYO6rorm4jOc+gHjDl8j1xhZ5OXR82zFY/6ZCkt26JQA8tddUG4tlbJi5+HUsJ3PTIIx5SD2HTt6aRJQ4geJHBCCQuP3y3Hpb7R6dVoStmouafFvap/kDwtHXnmRPgTRE6yd/+nMu6vEAyvB8XU6/X1AZtdKB8pRJ1zFhgOQRFPOilDeCC0mpjvwY=
after_success:
- codecov
