language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run computer-vision-api.py
after_success:
  - codecov
