language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
  secure: YDmysAjbWWJFcjkHh33BLde9d5wQnF/UsyUTSL+QsJpOsiRobXBqOS1cqwn0DMgRuCVwvZLDqkltOJKvDexq0b/iP0XqQp/M0nXpa++LgDcoFtAhdcNCtDamS+PGLSK7DHX+/TPRZEYxOn7fh2SeCEcr6AlFk7TwUtLbNnhZA7JQHxx6C9i5QGTmDFvI5iXa5qsB8VoT1mE4RpBrx4tEXTpcOYcPGUPtccT38rHySDVYjkt3Vf0Qa+CMdh1Q0v4sLLWwjZouP2uOb9bcK6hqAll32nRGBX5IuZN5Htat9xKlS0ZuAjRRECBYkIKw1r2XblI3O3Rd6pfnd6vI0ZMtKAlRtW5QCTtsKEHYEjMsOkY/c+BHo2QvZW0EzLiUCpehm3WNB+9q5MRvU/KfGqON+zbcyA/VtiUx+X2TBHAijIMLggpBWYceg9d1AuKL29/hyBfvjztFcM9gIP8obDcvB5GQZTBkEILSq/cAjX7y3Ab3Rb6FpQpnaDnHIPTGaMsBxSdfROlF0igZxMZ3zK4uzeSrWsTyaOrJVYDFGSlzUw+OPoDjz73smtn9ChszYAMitFVIKfhghM8wXiXaAb4OQ6q7gHrKKyH9/VN+yvGuJAbyxwlVGHeVROdABS4tHQYCYicuTUW5ScPoEeNx4Zc1l201Z65buZ9OFLC/8zNcbj8=
after_success:
- codecov
