language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- secure: gJPAB27VFtSu8bfRFX26GsIS0dK487pNLB0ZPZQ2pq44MbdilI3SXTcvvnHPaFceIf6soA6P4NnPGj0IfQQiQPUOmFvlc4MchkNTiiMdZ1Gwqnag4qMnQJm8oca0+VfYwn6zOx/lkjVx9oYCozGzmDOjQdxHJcNSFjZwFVVuaxLIR5v9yGT4NKqseppGqgquwX4SXva22tu+qQDubejYYNn23moKGxUGnmuAHIi9RtrcMb7zMNAo92WZvvhYL+ER9YyhIkvBo3WhHsGW+W5LnrP2Igc7E/Hr3Mq9ceAmZCqGTpLwdrXOwJujcrzXLeF7HhyZgzmItvGIbb4q6/3DCZNDGaWsQYzqx4hJsJQTyL5SM8TB+KfdhuhXPmiZg4k8PxUbHwQnyQasMQJ6V9SvHCsY1i/+Jmo2N2LNEnXylQo5qxOxNoqrmS+ZW+nmY147hZo6o2gRaM+9iqvQNpofQewfOunlLWKYljRi0H9zhOCVyoEY9y+waubFRRGVtIv+iXxCMvQsu3BDJwDsiSa/mdaEyB1psvEL5zY/VKeRqA8EA5XtmJEgwPTaXrJHQP+QMYYkNCo44Xcj3RsTPeiwpKDrjzZ0XjzqSmfi9M/zE1ybi42f6SFYRuosQBgLjTpKFJYc13PAkGsBqUYrI3fFKQQ1HuRbF+QmUU4wRJJpagk=
after_success:
- codecov
